name: Update Website

on:
  push:
    # any push without setting a version tag will update the website
    # when a file within the website directory is updated:
    tags-ignore:
      - 'v*'
    branches:
      - master
      - main
    paths:
      - 'website/**'

env:
  REQUIREMENTS: website/requirements.txt
  MKDOCS: website/mkdocs.yml
  WEBSITE: website/site

jobs:
  deploy:
    name: Update Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: 'Get Previous tag'
        # get previous tag in current branch (or v1.0.0 if no tag is found)
        id: version
        run: |
          echo "tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo v1.0.0)" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip
      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/${REQUIREMENTS}') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python3 -m pip install -r ./${REQUIREMENTS}

      - name: Setup doc deploy
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com

      - name: Update Website
        run: |
          mike deploy --config-file ./${MKDOCS} --push --update-aliases ${{ env.tag }} latest
          mike set-default --config-file ./${MKDOCS} --push latest

      - name: Copy Website to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${WEBSITE}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          tag_name: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
          full_commit_message: 'Deploy Website ${{ env.tag }}'
