name: Update Website

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits/branches

      - name: Extract Version Tag
        id: version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "::set-output name=tag::${GITHUB_REF#refs/tags/v(*.*).*}"

      - name: Summary
        run: |
          echo "version: ${{steps.extract.outputs.version}}"

      # - name: Setup Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.9'

      # - name: Upgrade pip
      #   run: |
      #     python3 -m pip install --upgrade pip

      # - name: Install dependencies
      #   run: python3 -m pip install -r ./requirements.txt

      # - name: Setup deploy
      #   run: |
      #     git config --global user.name github-actions[bot]
      #     git config --global user.email github-actions[bot]@users.noreply.github.com

      # - name: Deploy Website
      #   run: |
      #     mike deploy --push --update-aliases v4.4 latest
      #     mike set-default --push latest
